version: "3.7"
services:
  app:
    build: 
      context: .
    restart: always
    ports:
      - "9090:9090"
    environment:
      NODE_ENV: development
    depends_on:
      - "db"
    volumes:
      - ".:/usr/src/app"
    command: > 
      sh -c "npm run dev"

  db:
      image: "postgres:11"
      restart: always
      container_name: "postgres"
      environment: 
        - POSTGRES_USER=andrewchung
        - DB_HOST=postgres
        - POSTGRES_DB=nc_news
      ports:
        - "5432:5432"
volumes:
  my_dbdata: